# Generated by Django 4.1.3 on 2022-12-09 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customerportal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rider",
            name="lname",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="user_id",
        ),
        migrations.AddField(
            model_name="rider",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
