# Generated by Django 4.1.3 on 2022-12-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerportal", "0002_remove_rider_lname_remove_rider_user_id_rider_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="consigneeContact",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="consigneeEmail",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="consigneeName",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="destination",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="weight",
            field=models.FloatField(),
        ),
    ]
