# Generated by Django 4.1.3 on 2022-12-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "customerportal",
            "0004_remove_parcel_contact_remove_parcel_destination_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="parcel",
            old_name="province",
            new_name="state",
        ),
    ]
