# Generated by Django 4.1.3 on 2022-12-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerportal", "0006_parcel_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="pcity",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="pcountry",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="pstate",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
