# Generated by Django 4.1.3 on 2022-12-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerportal", "0007_parcel_pcity_parcel_pcountry_parcel_pstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(null=True),
        ),
    ]
