# Generated by Django 4.1.3 on 2023-01-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customerportal", "0008_alter_customer_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignParcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customerportal.parcel",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customerportal.rider",
                    ),
                ),
            ],
        ),
    ]
